sudo: required
services:
   - docker

script:
   - docker pull debian:jessie
   - docker build -t 3dpro/apt-cacher-ng .
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - docker push 3dpro/apt-cacher-ng
